# Generated by Django 4.2.1 on 2023-05-24 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news'),
            preserve_default=False,
        ),
    ]
