# Generated by Django 4.2.1 on 2023-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.CharField(max_length=200),
        ),
    ]
