# Generated by Django 4.2.1 on 2023-05-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_about_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_box', models.CharField(max_length=10)),
                ('address_one', models.CharField(max_length=40)),
                ('address_two', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.EmailField(max_length=254)),
            ],
        ),
    ]
