# Generated by Django 4.2.1 on 2023-05-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(max_length=30),
        ),
    ]
