# Generated by Django 4.2.1 on 2023-05-25 03:35

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contact_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
